[build]
  command = "bash scripts/build.sh"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_VERSION = "10.8.2"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20.18.0"

[context.deploy-preview.environment] 
  NODE_ENV = "production"
  NODE_VERSION = "20.18.0"